## Homework 2

### João Vitor de Oliveira Silva
### MATH 7665

In [88]:
using LinearAlgebra
using PlotlyJS

## Exercise 7

In [89]:
A = [0 1 2;2 0 1;1 2 0]

3×3 Matrix{Int64}:
 0  1  2
 2  0  1
 1  2  0

In [90]:
eigvals, V = eigen(A);

In [91]:
D = diagm(eigvals)

3×3 Matrix{ComplexF64}:
 -1.5-0.866025im   0.0+0.0im       0.0+0.0im
  0.0+0.0im       -1.5+0.866025im  0.0+0.0im
  0.0+0.0im        0.0+0.0im       3.0+0.0im

In [92]:
V

3×3 Matrix{ComplexF64}:
   0.57735-0.0im    0.57735+0.0im  0.57735+0.0im
 -0.288675+0.5im  -0.288675-0.5im  0.57735+0.0im
 -0.288675-0.5im  -0.288675+0.5im  0.57735+0.0im

In [93]:
opnorm(A - V * D * V', 1)

3.3306690738754696e-15

We notice that the eigendecomposition is correct, since $\|A - V_{num} D_{num} V_{num}^H\| < 10^{-15}$

In [94]:
function circulant_mat(n)
    M = zeros(n, n)
    for k = 1:n
        M[:, k] = cat(collect(k-1:-1:0), collect(n-1:-1:k), dims = 1)
    end
    return M
end

circulant_mat (generic function with 1 method)

In [95]:
# Testing to check if results are correct
C = circulant_mat(3);
eigvals, V = eigen(C);
D = diagm(eigvals);
diffval = opnorm(C - V * D * V', 1);
println("C = ")
display(C)
println("V = ")
display(V)
println("D = ")
display(D)
println("||A - VDV^H|| = ", diffval)

C = 


3×3 Matrix{Float64}:
 0.0  1.0  2.0
 2.0  0.0  1.0
 1.0  2.0  0.0

V = 


3×3 Matrix{ComplexF64}:
   0.57735-0.0im    0.57735+0.0im  0.57735+0.0im
 -0.288675+0.5im  -0.288675-0.5im  0.57735+0.0im
 -0.288675-0.5im  -0.288675+0.5im  0.57735+0.0im

D = 


3×3 Matrix{ComplexF64}:
 -1.5-0.866025im   0.0+0.0im       0.0+0.0im
  0.0+0.0im       -1.5+0.866025im  0.0+0.0im
  0.0+0.0im        0.0+0.0im       3.0+0.0im

||A - VDV^H|| = 3.3306690738754696e-15


In [96]:
# Testing to check if results are correct
C = circulant_mat(4);
eigvals, V = eigen(C);
D = diagm(eigvals);
diffval = opnorm(C - V * D * V', 1);
println("C = ")
display(C)
println("V = ")
display(V)
println("D = ")
display(D)
println("||A - VDV^H|| = ", diffval)

C = 


4×4 Matrix{Float64}:
 0.0  1.0  2.0  3.0
 3.0  0.0  1.0  2.0
 2.0  3.0  0.0  1.0
 1.0  2.0  3.0  0.0

V = 


4×4 Matrix{ComplexF64}:
          0.5-0.0im          …  -0.5+0.0im  0.5+0.0im
 -2.75337e-17+0.5im              0.5+0.0im  0.5+0.0im
         -0.5+1.38943e-17im     -0.5+0.0im  0.5+0.0im
  1.79984e-16-0.5im              0.5+0.0im  0.5+0.0im

D = 


4×4 Matrix{ComplexF64}:
 -2.0-2.0im   0.0+0.0im   0.0+0.0im  0.0+0.0im
  0.0+0.0im  -2.0+2.0im   0.0+0.0im  0.0+0.0im
  0.0+0.0im   0.0+0.0im  -2.0+0.0im  0.0+0.0im
  0.0+0.0im   0.0+0.0im   0.0+0.0im  6.0+0.0im

||A - VDV^H|| = 1.0130818220192422e-14


In [97]:
# Checking errors as n increases to infinity
max_size = 500
println("Size", "; ||A - VDV^H||")
for k = 1:10:(max_size+1)
    A = circulant_mat(k);
    eigvals, V = eigen(A);
    D = diagm(eigvals);
    diffval = opnorm(A - V * D * V', 1)
    println(k,";", diffval)
end

Size; ||A - VDV^H||
1;0.0
11;7.597198387890618e-14
21;5.311587362615064e-13
31;9.326336927943295e-13
41;1.874391037990533e-12
51;3.936101470043644e-12
61;5.293616048800542e-12
71;1.3084333117926126e-11
81;1.4442684130497681e-11
91;1.7669531201490437e-11
101;2.2769263335144905e-11
111;2.6313128084767876e-11
121;4.022868205547667e-11
131;5.436884696227777e-11
141;7.486114066212887e-11
151;7.306957972453926e-11
161;8.689740942445761e-11
171;1.0858358201060841e-10
181;1.1541624470937607e-10
191;1.505035012890784e-10
201;1.4685710333894208e-10
211;2.0145142331441834e-10
221;2.352915685493198e-10
231;2.486381092032257e-10
241;3.186592050421009e-10
251;3.182325892542735e-10
261;3.3956346032669335e-10
271;4.197615750790502e-10
281;4.797766204153768e-10
291;5.661359932239958e-10
301;5.837101867052081e-10
311;6.326041355347485e-10
321;7.224027770217056e-10
331;7.379475537024074e-10
341;7.750882725066096e-10
351;7.971066569965118e-10
361;9.285856228111645e-10
371;8.984729836418976e-10
381;9.32803

The error increases, which is expected since the number of floating point operations increase as the matrix size increases.

## Exercise 13

In [168]:
v1 = randn(2, 1)

2×1 Matrix{Float64}:
 -0.07041547850481787
  1.095347698752643

In [169]:
X = zeros(2, 2)
X[:, 1] = v1

2×1 Matrix{Float64}:
 -0.07041547850481787
  1.095347698752643

In [170]:
k = 30
for i = 1:k
    X[:, 2] = v1 + randn(2, 1)/(2^i)
    A = X * diagm([1, -1]) * inv(X)
    print("X = ")
    display(X)
    print("A = ")
    display(A)
    println("sigma_1 = ", opnorm(A))
end

X = 

2×2 Matrix{Float64}:
 -0.0704155  0.940603
  1.09535    0.377373

A = 

2×2 Matrix{Float64}:
 -0.949713  -0.125339
 -0.782232   0.949713

sigma_1 = 1.3810038324575271
X = 

2×2 Matrix{Float64}:
 -0.0704155  0.089183
  1.09535    1.15037

A = 

2×2 Matrix{Float64}:
  -0.0933581  -0.0702876
 -14.1033      0.0933581

sigma_1 = 14.103878877037415
X = 

2×2 Matrix{Float64}:
 -0.0704155  0.0553197
  1.09535    1.18423

A = 

2×2 Matrix{Float64}:
   0.158309  -0.0541089
 -18.0181    -0.158309

sigma_1 = 18.01946547550979
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0776497
  1.09535     1.07682

A = 

2×2 Matrix{Float64}:
 -17.4328  -1.18497
 255.62    17.4328

sigma_1 = 256.80896410825585
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0642476
  1.09535     1.06677

A = 

2×2 Matrix{Float64}:
   30.6692    1.90731
 -492.629   -30.6692

sigma_1 = 494.5386971897766
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.075663
  1.09535     1.09218

A = 

2×2 Matrix{Float64}:
 -26.7599  -1.78457
 400.707   26.7599

sigma_1 = 402.49432583990387
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0627802
  1.09535     1.10005

A = 

2×2 Matrix{Float64}:
   16.8182    1.01689
 -277.171   -16.8182

sigma_1 = 278.1911022692797
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0692496
  1.09535     1.08882

A = 

2×2 Matrix{Float64}:
   186.608    11.932
 -2918.34   -186.608

sigma_1 = 2930.2700136818185
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0709779
  1.09535     1.09788

A = 

2×2 Matrix{Float64}:
 -353.947  -22.8181
 5490.26   353.947

sigma_1 = 5513.079516532183
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0703088
  1.09535     1.09519

A = 

2×2 Matrix{Float64}:
   1456.55     93.5716
 -22672.9   -1456.55

sigma_1 = 22766.518430664608
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0708661
  1.09535     1.09491

A = 

2×2 Matrix{Float64}:
 -295.035  -19.0309
 4573.85   295.035

sigma_1 = 4592.884437085185
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0705716
  1.09535     1.09547

A = 

2×2 Matrix{Float64}:
  -949.2  -61.0845
 14749.7  949.2

sigma_1 = 14810.810969226834
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0701965
  1.09535     1.09518

A = 

2×2 Matrix{Float64}:
    674.992    43.3282
 -10515.4    -674.992

sigma_1 = 10558.722597200145
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0703744
  1.09535     1.09537

A = 

2×2 Matrix{Float64}:
   3301.03    212.146
 -51364.7   -3301.03

sigma_1 = 51576.881174664406
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0704074
  1.09535     1.09539

A = 

2×2 Matrix{Float64}:
   12893.0     828.776
 -200573.0  -12893.0

sigma_1 = 201401.75844095924
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.070413
  1.09535     1.09534

A = 

2×2 Matrix{Float64}:
 63944.5          4110.67
    -9.94704e5  -63944.5

sigma_1 = 998814.3214379725
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.070414
  1.09535     1.09535

A = 

2×2 Matrix{Float64}:
 93337.1          6000.2
    -1.45192e6  -93337.1

sigma_1 = 1.4579211876791602e6
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0704214
  1.09535     1.09535

A = 

2×2 Matrix{Float64}:
 -25266.4        -1624.34
      3.93015e5  25266.4

sigma_1 = 394639.57004972483
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0704171
  1.09535     1.09535

A = 

2×2 Matrix{Float64}:
 -88859.1        -5712.45
      1.38223e6  88859.1

sigma_1 = 1.3879437384076845e6
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0704139
  1.09535     1.09535

A = 

2×2 Matrix{Float64}:
 86083.9          5533.92
    -1.33909e6  -86083.9

sigma_1 = 1.3446277542814508e6
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0704156
  1.09535     1.09535

A = 

2×2 Matrix{Float64}:
 -1.0136e6   -65160.5
  1.57671e7       1.0136e6

sigma_1 = 1.5832237712725533e7
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0704157
  1.09535     1.09535

A = 

2×2 Matrix{Float64}:
 -6.33308e5  -40712.9
  9.85141e6       6.33308e5

sigma_1 = 9.892122158427045e6
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0704155
  1.09535     1.09535

A = 

2×2 Matrix{Float64}:
 -1.13959e7  -7.32593e5
  1.77268e8   1.13959e7

sigma_1 = 1.7800072388390175e8
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0704154
  1.09535     1.09535

A = 

2×2 Matrix{Float64}:
  4.00777e6  257643.0
 -6.23428e7      -4.00777e6

sigma_1 = 6.26004458451081e7
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0704155
  1.09535     1.09535

A = 

2×2 Matrix{Float64}:
 -9.55789e6  -6.14438e5
  1.48678e8   9.55789e6

sigma_1 = 1.4929214843942982e8
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0704154
  1.09535     1.09535

A = 

2×2 Matrix{Float64}:
  4.45849e6   2.86618e5
 -6.93541e7  -4.45849e6

sigma_1 = 6.964069058629775e7
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0704155
  1.09535     1.09535

A = 

2×2 Matrix{Float64}:
 -6.20422e7  -3.98844e6
  9.65098e8   6.20422e7

sigma_1 = 9.690860324934976e8
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0704155
  1.09535     1.09535

A = 

2×2 Matrix{Float64}:
  4.29497e8   2.76107e7
 -6.68105e9  -4.29497e8

sigma_1 = 6.708656008289416e9
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0704155
  1.09535     1.09535

A = 

2×2 Matrix{Float64}:
  5.02639e7   3.23126e6
 -7.8188e8   -5.02639e7

sigma_1 = 7.851116553773296e8
X = 

2×2 Matrix{Float64}:
 -0.0704155  -0.0704155
  1.09535     1.09535

A = 

2×2 Matrix{Float64}:
  1.37927e8   8.86675e6
 -2.14552e9  -1.37927e8

sigma_1 = 2.1543841552769e9


In [171]:
v1 = rand(2, 1)

2×1 Matrix{Float64}:
 0.2718163812584051
 0.9626887604599392

In [172]:
X = zeros(2, 2)
X[:, 1] = v1

2×1 Matrix{Float64}:
 0.2718163812584051
 0.9626887604599392

In [174]:
k = 30
for i = 1:k
    X[:, 2] = v1 + rand(2, 1)/(2^i)
    A = X * diagm([1, -1]) * inv(X)
    print("X = ")
    display(X)
    print("A = ")
    display(A)
    println("sigma_1 = ", opnorm(A))
end

X = 

2×2 Matrix{Float64}:
 0.271816  0.592113
 0.962689  0.963549

A = 

2×2 Matrix{Float64}:
 -2.70009  1.04472
 -6.02117  2.70009

sigma_1 = 7.204693246374041
X = 

2×2 Matrix{Float64}:
 0.271816  0.29778
 0.962689  0.964791

A = 

2×2 Matrix{Float64}:
 -22.4751   6.62822
 -76.0581  22.4751

sigma_1 = 82.69837936543468
X = 

2×2 Matrix{Float64}:
 0.271816  0.279484
 0.962689  0.969997

A = 

2×2 Matrix{Float64}:
  -98.7515  28.165
 -346.205   98.7515

sigma_1 = 374.3728410036576
X = 

2×2 Matrix{Float64}:
 0.271816  0.288013
 0.962689  0.991311

A = 

2×2 Matrix{Float64}:
  -69.9835  20.0423
 -244.318   69.9835

sigma_1 = 264.3639816891434
X = 

2×2 Matrix{Float64}:
 0.271816  0.274997
 0.962689  0.981626

A = 

2×2 Matrix{Float64}:
 254.915   -71.6933
 906.372  -254.915

sigma_1 = 978.066391844202
X = 

2×2 Matrix{Float64}:
 0.271816  0.284881
 0.962689  0.965317

A = 

2×2 Matrix{Float64}:
  -45.2381  13.0554
 -156.678   45.2381

sigma_1 = 169.73896085725994
X = 

2×2 Matrix{Float64}:
 0.271816  0.275387
 0.962689  0.967438

A = 

2×2 Matrix{Float64}:
 -246.054   69.756
 -867.905  246.054

sigma_1 = 937.6621935368704
X = 

2×2 Matrix{Float64}:
 0.271816  0.272981
 0.962689  0.963172

A = 

2×2 Matrix{Float64}:
  -530.125  149.964
 -1874.0    530.125

sigma_1 = 2023.9606869198062
X = 

2×2 Matrix{Float64}:
 0.271816  0.273642
 0.962689  0.964506

A = 

2×2 Matrix{Float64}:
  -416.091  117.766
 -1470.12   416.091

sigma_1 = 1587.8897691523623
X = 

2×2 Matrix{Float64}:
 0.271816  0.272465
 0.962689  0.96319

A = 

2×2 Matrix{Float64}:
 -1072.97   303.238
 -3796.59  1072.97

sigma_1 = 4099.831641500573
X = 

2×2 Matrix{Float64}:
 0.271816  0.272249
 0.962689  0.962768

A = 

2×2 Matrix{Float64}:
 -1326.85   374.92
 -4695.74  1326.85

sigma_1 = 5070.662425744529
X = 

2×2 Matrix{Float64}:
 0.271816  0.271995
 0.962689  0.962751

A = 

2×2 Matrix{Float64}:
  -3378.07   954.086
 -11960.5   3378.07

sigma_1 = 12914.627678618048
X = 

2×2 Matrix{Float64}:
 0.271816  0.271839
 0.962689  0.962764

A = 

2×2 Matrix{Float64}:
 -3.57333e5  1.00894e5
 -1.26556e6  3.57333e5

sigma_1 = 1.3664513227358805e6
X = 

2×2 Matrix{Float64}:
 0.271816  0.271876
 0.962689  0.962745

A = 

2×2 Matrix{Float64}:
 -12439.9   3512.69
 -44054.6  12439.9

sigma_1 = 47567.24723614944
X = 

2×2 Matrix{Float64}:
 0.271816  0.271833
 0.962689  0.96269

A = 

2×2 Matrix{Float64}:
 -33168.4         9365.41
     -1.17468e5  33168.4

sigma_1 = 126833.85391527538
X = 

2×2 Matrix{Float64}:
 0.271816  0.271829
 0.962689  0.962694

A = 

2×2 Matrix{Float64}:
 -49554.4        13992.0
     -1.75503e5  49554.4

sigma_1 = 189494.8038398776
X = 

2×2 Matrix{Float64}:
 0.271816  0.271819
 0.962689  0.962689

A = 

2×2 Matrix{Float64}:
 -2.72726e5  77004.7
 -9.65906e5      2.72726e5

sigma_1 = 1.042910665716362e6
X = 

2×2 Matrix{Float64}:
 0.271816  0.27182
 0.962689  0.962691

A = 

2×2 Matrix{Float64}:
 -1.72836e5  48800.9
 -6.12129e5      1.72836e5

sigma_1 = 660930.0740073607
X = 

2×2 Matrix{Float64}:
 0.271816  0.271817
 0.962689  0.962689

A = 

2×2 Matrix{Float64}:
 -3.70858e6  1.04712e6
 -1.31346e7  3.70858e6

sigma_1 = 1.4181760239069102e7
X = 

2×2 Matrix{Float64}:
 0.271816  0.271817
 0.962689  0.96269

A = 

2×2 Matrix{Float64}:
 -8.88806e5  2.50956e5
 -3.14787e6  8.88806e5

sigma_1 = 3.3988261853903746e6
X = 

2×2 Matrix{Float64}:
 0.271816  0.271817
 0.962689  0.962689

A = 

2×2 Matrix{Float64}:
 -1.2496e6   3.52826e5
 -4.42569e6  1.2496e6

sigma_1 = 4.778513825457558e6
X = 

2×2 Matrix{Float64}:
 0.271816  0.271817
 0.962689  0.962689

A = 

2×2 Matrix{Float64}:
 -3.14158e6  8.8703e5
 -1.11265e7  3.14158e6

sigma_1 = 1.2013526303305365e7
X = 

2×2 Matrix{Float64}:
 0.271816  0.271816
 0.962689  0.962689

A = 

2×2 Matrix{Float64}:
 -9.24248e7  2.60963e7
 -3.2734e8   9.24248e7

sigma_1 = 3.5343602521186733e8
X = 

2×2 Matrix{Float64}:
 0.271816  0.271816
 0.962689  0.962689

A = 

2×2 Matrix{Float64}:
 -2.39796e8  6.77068e7
 -8.49284e8  2.39796e8

sigma_1 = 9.169910908551826e8
X = 

2×2 Matrix{Float64}:
 0.271816  0.271816
 0.962689  0.962689

A = 

2×2 Matrix{Float64}:
 -4.75477e7  1.34252e7
 -1.68399e8  4.75477e7

sigma_1 = 1.8182431866049904e8
X = 

2×2 Matrix{Float64}:
 0.271816  0.271816
 0.962689  0.962689

A = 

2×2 Matrix{Float64}:
 -5.67973e7  1.60368e7
 -2.01158e8  5.67973e7

sigma_1 = 2.1719502817352536e8
X = 

2×2 Matrix{Float64}:
 0.271816  0.271816
 0.962689  0.962689

A = 

2×2 Matrix{Float64}:
 -3.12608e8  8.82652e7
 -1.10716e9  3.12608e8

sigma_1 = 1.1954246474777265e9
X = 

2×2 Matrix{Float64}:
 0.271816  0.271816
 0.962689  0.962689

A = 

2×2 Matrix{Float64}:
 -2.09233e8  5.90771e7
 -7.41037e8  2.09233e8

sigma_1 = 8.001138090088948e8
X = 

2×2 Matrix{Float64}:
 0.271816  0.271816
 0.962689  0.962689

A = 

2×2 Matrix{Float64}:
 -5.65879e8  1.59777e8
 -2.00417e9  5.65879e8

sigma_1 = 2.1639424826742525e9
X = 

2×2 Matrix{Float64}:
 0.271816  0.271816
 0.962689  0.962689

A = 

2×2 Matrix{Float64}:
 -8.25301e8  2.33025e8
 -2.92296e9  8.25301e8

sigma_1 = 3.1559835127868624e9


If the first column $[Xe_1]_i \sim \mathcal{N}(0, 1), i = 1,2$  or $[Xe_1]_i \sim \mathcal{U}([0, 1]), i = 1,2$, after some experiments as $[Xe_2] \to [Xe_1]$, $\sigma_1$ appears to blow to +$\infty$.
This is somewhat expected, since the eigenvector basis matrix $X$ is becoming very ill conditioned, which strongly affects $A$ (that is expressed in terms of its inverse).